project:
  name: quickstart-cherwell
  owner: quickstart-eng@amazon.com
  package_lambda: false
  shorten_stack_name: true
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - us-east-1
tests:
  cherwell:
    parameters:
      ClientID: 00000000000-0000000000-000000
      ConfigRules: "True"
      DeployAWSConfigSupport: "True"
      EnableAWSConfigRecorder: "True"
      Grant: password
      IncludeGlobalResourceTypes: "False"
      Password: CSDAdmin
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-cherwell/
      Url: http://yourserver.com
      Username: CSDAdmin
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - sa-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    template: templates/cherwell-master.template.yaml
  cherwell-noconfig:
    parameters:
      ClientID: "0000000000000000000000000000000"
      ConfigRules: "True"
      DeployAWSConfigSupport: "False"
      EnableAWSConfigRecorder: "True"
      Grant: password
      IncludeGlobalResourceTypes: "False"
      Password: CSDAdmin
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-cherwell/
      Url: http://yourserver
      Username: CSDAdmin
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - sa-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-east-1
    template: templates/cherwell-master.template.yaml
